config/routes.rb
Rails.application.routes.draw do



  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "welcome#index"
  resources :topics do
    resources :bookmarks, except: [:index]
  end
  get "/bookmarks", to: "bookmarks#index", as: "user_bookmarks"
  get "/likes/new", to: "likes#new", as: "new_like"
  post "/likes", to: "likes#create", as: "create_like"
  delete "/likes/:id", to: "likes#destroy", as: "delete_like"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  has_many :likes
  validates :url, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :bookmark

  validates_uniqueness_of :user_id, scope: :bookmark_id
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  belongs_to :user

  before_validation :regulate_title
  validates :title, presence: true, uniqueness: { case_sensitive: false }


  private

  #strip and downcase the title 
  def regulate_title
    self.title = self.title.strip
    self.title.downcase!
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  enum role: [:member, :admin]

  validates :user_name, presence: true, uniqueness: true

  before_save { self.role ||= :member }
  has_many :bookmarks, dependent: :destroy
  has_many :likes
  has_many :topics

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    added_attrs = [:user_name, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :authenticate_user!

  def index
    @bookmarks = Bookmark.where(user_id: current_user.id)
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.new
    @user = current_user
  end

  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @bookmark = @topic.bookmarks.create(bookmark_params)
    @bookmark.user_id = current_user.id

    if @bookmark.save!
      flash[:notice] = "Bookmark Was Saved"
      redirect_to @topic
    else
      flash.now[:alert] = "There was an error creating a Bookmark"
      render :new
    end
  end

  def update
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])
    @bookmark.assign_attributes(bookmark_params)

    if @bookmark.save!
      flash[:notice] = "Bookmark Was Updated"
      redirect_to @topic
    else
      flash.now[:alert] = "Server Error. Bookmark not Updated"
      render :edit
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    if @bookmark.destroy!
      flash[:notice] = "Bookmark was deleted"
      redirect_to action: :index
    else
      flash.now[:error] = "Error in deleting the bookmark"
      render :index
    end
  end

  private
  def bookmark_params
    params.require(:bookmark).permit(:url, :description)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @like = Like.new(like_params)
    @topic_id = params[:topic_id]
    if @like.save!
      flash[:notice] = "Bookmark liked"
      redirect_to topic_path(id: @topic_id)
    else
      flash[:alert] = "Error in saving like"
      redirect_to topic_path(id: @topic_id)
    end
  end

  def destroy
    @like = Like.find(params[:id])
    @topic_id = params[:topic_id]
    if @like.destroy!
      flash[:notice] = "BOOOO! Unliked!"
      redirect_to topic_path(id: @topic_id)
    else
      flash[:alert] = "Couldn't reverse like"
      redirect_to topic_path(id: @topic_id)
    end
  end

  private
  def like_params
    params.permit(:user_id, :bookmark_id)
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  def index
    @topics = Topic.all
  end

  def new
    @topic = Topic.new
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def show
    @topic = Topic.find(params[:id])
    @topic_bookmarks = Bookmark.where(topic_id: @topic.id)
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user.id

    if @topic.save
      flash[:notice] = "Topic successfully created"
      redirect_to(topics_path)
    else
      if @topic.errors
        flash.now[:alert] = "There was an error creating a topic"
        render(:new)
      end
    end
  end

  def update
    @topic = Topic.find(params[:id])
    @topic.assign_attributes(topic_params)
    @topic.user_id = current_user.id

    if @topic.save
      flash[:notice] = "Topic successfully updated"
      redirect_to(topics_path)
    else
      if @topic.errors
        flash.now[:alert] = "There was an error updating a topic"
        render(:new)
      end
    end
  end

  def destroy
    @topic = Topic.find(params[:id])

    if @topic.destroy && (@topic.bookmarks.count == 0)
      flash[:notice] = "Topic was successfully deleted!"
      redirect_to(topics_path)
    else
      flash.now[:alert] = "Cannot delete topic!"
      redirect_to(topics_path)
    end
  end

  def topic_params
    params.require(:topic).permit(:title)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @bookmarks = Bookmark.limit(10).order("RANDOM()")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/topic_helper.rb
module TopicHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <h2 class="col-md-8 offset-md-2">Create a New Bookmark</h2>
  </div>
  <div class="row">
    <div class="col-md-8 offset-md-2">
    <%= form_for([@topic, @bookmark]) do |f| %>
      <div class="form-group">
        <%= f.label :url %><br />
        <div>
        <%= f.text_area :url, cols: 100, autofocus: true, autocomplete: "off" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :description %><br />
        <div>
        <%= f.text_area :description, cols: 100, rows: 10, autocomplete: "off" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.submit "Create Bookmark", class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
  </div>
</div>

app/views/bookmarks/index.html.erb
<div class="container-fluid bookmarks-index-container">
  <% @bookmarks.each do |bookmark| %>
  <div class="my-bookmark-window">
      <h3><%= link_to bookmark.url, "http://#{bookmark.url}" %></h3>
      <p><%=bookmark.description %></p>
      <p>Created By: <%= User.where(id: bookmark.user_id).pluck(:user_name)[0] %></p>
      <div class="bookmark-control-btns">
        <div class="more-btn">
          <%= link_to "Show More!", topic_bookmark_path(bookmark.topic_id, bookmark) %>
        </div>
        <div class="delete-bookmark">
          <%= link_to "DELETE", topic_bookmark_path(bookmark.topic_id, bookmark), method: :delete %>
        </div>
      </div>
  </div>
  <% end %>
</div>

app/views/bookmarks/new.html.erb
<div class="container-fluid">
  <div class="row">
    <h2 class="col-md-8 offset-md-2">Create a New Bookmark</h2>
  </div>
  <div class="row">
    <div class="col-md-8 offset-md-2">
    <%= form_for([@topic, @bookmark]) do |f| %>
      <div class="form-group">
        <%= f.label :url %><br />
        <div>
        <%= f.text_area :url, cols: 100, autofocus: true, autocomplete: "off" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :description %><br />
        <div>
        <%= f.text_area :description, cols: 100, rows: 10, autocomplete: "off" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.submit "Create Bookmark", class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
  </div>
</div>

app/views/bookmarks/show.html.erb
<h1>Bookmarks#show</h1>
<p>Find me in app/views/bookmarks/show.html.erb</p>

app/views/bookmarks/update.html.erb
<h1>Bookmarks#update</h1>
<p>Find me in app/views/bookmarks/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocmarks</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-company-red">
      <a class="navbar-brand" href="/">Home</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link" href="/topics">All <span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link" href="#">Sports</a>
          <a class="nav-item nav-link" href="#">Science</a>
          <a class="nav-item nav-link" href="#">Games</a>
        </div>
        <div class = "navbar-nav ml-auto">
        <% if user_signed_in? %>
        <div class="nav-user-name">
          <span>Hello: <%= current_user.user_name.upcase %></span>
        </div>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle dropdown-button" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            My BlocMarks
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="/:topic_id/bookmarks/new">Create a Bookmark</a>
            <a class="dropdown-item" href="/topics/new">Create a Topic</a>
            <a class="dropdown-item" href="/bookmarks">Show My Bookmarks</a>
            <a class="dropdown-item" href="#">My Profile</a>
          </div>
        </div>
        <%= link_to "Sign Out", destroy_user_session_path, class: "nav-item nav-link", method: :delete %>
        <% else %>
        <%= link_to "Sign In", new_user_session_path, class: "nav-item nav-link" %>
        <%= link_to "Sign Up", new_user_registration_path, class: "nav-item nav-link" %>
        <% end %>
        </div>
      </div>
    </nav>
    <% if !flash.empty? %>
        <% flash.keys.each do |key| %>
          <div class="alert alert-warning alert-dismissable">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <p><%= flash[key] %></p>
            <% puts flash[key] %>
          </div>
        <% end %>
    <% end %>
    <%= yield %>
  </body>
  <nav class="navbar navbar-expand-lg navbar-light bg-company-red">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <div class"nav-item nav-link">facebook</div>
        <div class"nav-item nav-link">facebook</div>
        <div class"nav-item nav-link">facebook</div>
      </div>
    </div>
  </nav>
</html>

app/views/likes/new.html.erb
<p>New field for likes</p>

app/views/topics/create.html.erb
<h1>Topic#:create</h1>
<p>Find me in app/views/topic/:create.html.erb</p>

app/views/topics/edit.html.erb
<% if !@topic.errors.empty? %>
  <% @topic.errors.full_messages.each do |message| %>
  <div class="alert alert-danger alert-dismissable">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <p><%= message %></p>
  </div>
  <% end %>
<% end %>
<div class="container-fluid topic-container">
  <div class="row">
    <h2 class="col-md-8 offset-md-2">New Topic</h2>
  </div>
  <div class="row">
    <div class="col-md-8 offset-md-2">
    <%= form_for(@topic) do |f| %>
      <div class="form-group">
        <%= f.label :title %><br />
        <div>
        <%= f.text_area :title, cols: 100, autofocus: true, autocomplete: "off" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.submit "Submit Changes", class: "btn btn-success" %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/topics/index.html.erb
<div class="container-fluid topic-container">
  <% @topics.each do |topic| %>
  <div class="topic-window">
    <h3><%= topic.title %></h3>
    <p>Created By: <%= User.where(:id => topic.user_id).pluck(:user_name).join %></p>
    <div class="topic-control-section">
      <div class="topic-more-btn">
        <%= link_to "Explore", topic_path(topic.id) %>
      </div>
      <% if (topic.user_id == current_user.id) || (current_user.role == "admin") %>
      <div class="delete-btn">
        <%= button_to "DELETE", topic, method: :delete %>
      </div>
      <% end %>
    </div>
  </div>
  <% end %>
</div>

app/views/topics/new.html.erb
<% if !@topic.errors.empty? %>
  <% @topic.errors.full_messages.each do |message| %>
  <div class="alert alert-danger alert-dismissable">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <p><%= message %></p>
  </div>
  <% end %>
<% end %>
<div class="container-fluid topic-container">
  <div class="row">
    <h2 class="col-md-8 offset-md-2">New Topic</h2>
  </div>
  <div class="row">
    <div class="col-md-8 offset-md-2">
    <%= form_for(@topic) do |f| %>
      <div class="form-group">
        <%= f.label :title %><br />
        <div>
        <%= f.text_area :title, cols: 100, autofocus: true, autocomplete: "off" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.submit "Create Topic", class: "btn btn-success" %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/topics/show.html.erb
<div class="container-fluid topic-page-container">
  <div class="topic-title">
    <h3>Category:  <span><%= @topic.title.upcase %></span> </h3>
  </div>
  <div class="topic-control-btns">
    <%= link_to "New Bookmark", {action: :new, controller: :bookmarks, topic_id: @topic.id}, method: :get, class: "bookmark-create-btn" %>
    <% if (@topic.user_id == current_user.id) || (current_user.role == "admin") %>
      <%= link_to "Delete Topic", {action: :destroy, controller: :topics, id: @topic.id}, method: :delete, class: "topic-destroy-btn" %>
      <%= link_to "Edit Topic", {action: :edit, controller: :topics, id: @topic.id}, method: :get, class: "topic-edit-btn" %>
    <% end  %>
  </div>
  <div class="container-fluid bookmarks-container">
    <% @topic_bookmarks.each do |bookmark| %>
      <div class="bookmark-window">
        <p class="bookmark-url"><%= link_to bookmark.url, "http://#{bookmark.url}" %></p>
        <p class="bookmark-description"><%= bookmark.description %></p>
        <div class="bookmark-likes">
          <div class="like-button">
          <% if !bookmark.likes.exists?(user_id: current_user.id) %>
            <%= button_to "Like", { controller: "likes", action: "create"}, params: { user_id: current_user.id, bookmark_id: bookmark.id, topic_id: @topic }, class: "like-btn", method: :post  %>
          <% else %>
            <% like_id = bookmark.likes.where(:user_id => current_user.id ).pluck(:id)[0] %>
            <%= button_to "Unlike", delete_like_path(like_id), params: {topic_id: @topic}, class: "unlike-btn", method: :delete %>
          <% end %>
          </div>
          <div class="total-likes">
            <p><%= bookmark.likes.count %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/update.html.erb
<h1>Topic#:update</h1>
<p>Find me in app/views/topic/:update.html.erb</p>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <p class="text-center">Welcome </p>
  <div class="welcome-title"><h3>Welcome to BookMarks!</h3></div>
  <div class="welcome-description"><p>Create, Share, Read and Discover What Others Are Posting!</p></div>
</div>
<div class="container-fluid">
  <% @bookmarks.each do |bookmark| %>
  <div class="bookmark-window">
    <h3><%= bookmark.url %></h3>
    <p><%= bookmark.description %></p>
    <div class="index-like-btn">
      <button class="btn btn-link">Like!</button>
      <div class="bookmark-likes"><%=bookmark.likes.count%></div>
    </div>
  </div>
  <% end %>